### ISSUE TITLE
my penis

### ISSUE THREAD

**Issue by omgbox** [whoisandie/yoda#12]
> npm ERR! notsup Not compatible with your operating system or architecture: appdmg@0.3.6
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   linux
> npm ERR! notsup Actual Arch: x64

**Comment by whoisandy** [comment]
@omgbox This repository is no  longer maintained. Sorry for the trouble. And no profanity please!
