### ISSUE TITLE
Don't use @import

### ISSUE THREAD

**Issue by macjabeth** [whoisandie/yoda#4]
This is more of a suggestion than an issue, of course.

Compared to `<link>`, `@import` is slower, adds extra page requests, and can cause other unforeseen problems. Avoid them and instead opt for an alternate approach:
- Use multiple `<link>` elements
- Compile your CSS with a preprocessor like Sass or Less into a single file
- Concatenate your CSS files with features provided in Rails, Jekyll, and other environments
- For more information, [read this article by Steve Souders](http://www.stevesouders.com/blog/2009/04/09/dont-use-import/).

**Comment by whoisandy** [comment]
@bunster Thanks for the suggestion. There are no CSS imports used anywhere in the app. Its just one minified `style.css` file in the entire app, uses gulp to compile javascript and preprocess less files. Check out `gulpfile.js` for more details.

**Comment by whoisandy** [comment]
Check out https://github.com/whoisandie/yoda/blob/master/gulpfile.js#L95
